#!/bin/bash
set -e
set -x

ROOT=~/dev
mkdir -p $ROOT
cd $ROOT

rm -rf greent-venv
python3.6 -m venv greent-venv
source greent-venv/bin/activate

if [ -d greent ]; then
   git pull
else
   git clone git@github.com:NCATS-Tangerine/greent.git
fi
cd greent

pip install -r greent/requirements.txt
PYTHONPATH=$PWD green
./publish

pip install --no-cache-dir greent


