#!/bin/bash

cd $ROBOKOP_HOME/robokop-interfaces
export PYTHONPATH=$ROBOKOP_HOME/robokop-interfaces

export TRANSLATOR_SERVICES_ROSETTAGRAPH_URL="bolt://$NEO4J_HOST:$NEO4J_BOLT_PORT"
export CELERY_BROKER_URL="redis://$REDIS_HOST:$REDIS_PORT/$BUILDER_REDIS_DB"
export CELERY_RESULT_BACKEND="redis://$REDIS_HOST:$REDIS_PORT/$BUILDER_REDIS_DB"
export FLOWER_BROKER_API="redis://$REDIS_HOST:$REDIS_PORT/$BUILDER_REDIS_DB"
export FLOWER_PORT="$BUILDER_FLOWER_PORT"
export REDIS_DB="$GREENT_REDIS_DB"

if [[ -z CELERY_BROKER_URL ]]; then
    export CELERY_BROKER_URL="redis://$REDIS_HOST:$REDIS_PORT/$BUILDER_REDIS_DB"
fi
if [[ -z CELERY_RESULT_BACKEND ]]; then
    export CELERY_RESULT_BACKEND="redis://$REDIS_HOST:$REDIS_PORT/$BUILDER_REDIS_DB"
fi
if [[ -z FLOWER_PORT ]]; then
    export FLOWER_PORT=$BUILDER_FLOWER_PORT
fi

exec flower \
    -A builder.api.tasks.celery \
    --broker=$CELERY_BROKER_URL \
    --broker_api=$CELERY_BROKER_URL