#!/bin/bash
 
set -e

version=$1

#    package_dir={ 'greent' : 'greent' },
# http://peterdowns.com/posts/first-time-with-pypi.html

cat <<EOF > setup.py
from distutils.core import setup
from pip.req import parse_requirements

install_reqs = parse_requirements("greent/requirements.txt", session="i")
requirements = [str(r.req) for r in install_reqs]

setup(
    name = 'greent',
    packages = [ 'greent' ], # this must be the same as the name above
    package_data={ 'greent' : [
        'requirements.txt',
        'query/*.sparql'
    ]},
    version = '${version}',
    description = 'Green Team BioMedical Data Translator',
    author = 'Steve Cox',
    author_email = 'scox@renci.org',
    install_requires = requirements,
    include_package_data=True,
    url = 'https://github.com/NCATS-Tangerine/greent.git',
    download_url = 'http://github.com/NCATS-Tangerine/greent/archive/0.1.tar.gz',
    keywords = [ 'biomedical', 'environmental', 'exposure', 'clinical' ],
    classifiers = [ ],
)
EOF

if [ -z "$version" ]; then
    echo version parameter is required
    exit 0
fi

publish () {

    #python testgreent.py
    set -x

    git tag
    echo $version
    
    if [ -z "$( git tag | grep $version )" ]; then

	python setup.py sdist
	tar tf dist/greent-${version}.tar.gz
	twine upload --skip-existing dist/greent-${version}.tar.gz
	
	git commit -am "api version $version"
	git push origin master
	
	git tag $version -m "publishing version $version"
	git push --tags origin master
	


	f () {
	echo $version > flag
	python setup.py register -r pypitest
	python setup.py sdist upload -r pypitest
	python setup.py register -r pypi
	python setup.py sdist upload -r pypi
	}
    fi
    if [ "$( pip freeze | grep 'greent=' | grep -c greent )" -gt 0 ]; then
	python -m pip --no-cache-dir uninstall -y greent
    fi
    python -m pip --no-cache-dir install greent==$version

    cur=$PWD
    cd $(dirname $(which python))/../lib/pyth*/site-packages/
    python greent/testgreent.py
    cd $cur
}


publish $*
