prefix envo:  <http://identifiers.org/envo/ctd/resource/>
prefix mesh:  <http://bio2rdf.org/mesh:>
select ?exposure ?stressorAgentID ?stressorAgentName ?diseaseID where {

  values ( ?stressorAgentID ) {
#    ( mesh:D052638 "Particulate Matter"  )
    $stressorAgentIDs
  }

  ?exposure envo:stressoragentid     ?stressorAgentID ;
            envo:diseaseid           ?diseaseID ;
            envo:stressoragentname   ?stressorAgentName .
  filter regex(str(?diseaseID), ".*/mesh:.*")
}

