prefix kegg:      <http://chem2bio2rdf.org/kegg/resource/>
prefix drugbank:  <http://chem2bio2rdf.org/drugbank/resource/>
prefix ctd:       <http://chem2bio2rdf.org/ctd/resource/>
prefix mesh:      <http://bio2rdf.org/mesh:>
select ?drugGenericName ?uniprotGeneID ?pathwayName ?keggPath where {
    ?keggPath    kegg:protein                ?swissProtID ;
                 kegg:Pathway_name           ?pathwayName .
    ?keggInter   kegg:cid                    ?pubchemCID .
    ?dbInter     drugbank:GeneBank_ID        ?geneBankID ;
                 drugbank:SwissProt_ID       ?swissProtID ;
                 drugbank:gene               ?uniprotGeneID .
    ?drugID      drugbank:CID                ?pubchemCID ;
                 drugbank:Generic_Name       ?drugGenericName .
    ?ctd_disease ctd:diseaseid               ?diseaseID ;
                 ctd:cid                     ?pubchemCID .
    values ( ?diseaseID ) {
        ${diseaseMeshIDList}
    }
} LIMIT 2000