import yaml

header="""// DO NOT EDIT: GENERATED FILE
//THIS FILE IS GENERATED BY scripts/make_license_adoc.py USING source_licenses.yaml 
//IF UPDATES ARE NEEDED, MODIFY THE yaml AND REBUILD
== Data Sources, Licenses, and Attributions

Robokop KG is assembled from many data sources, some of which are also integrations of still other sources. This is a list of all data sources and sub-data sources, along with a link to their licensing information, and instructions for how each should be cited.

|===
|Data Source |License| Attribution

"""

mydata = yaml.load(open("../source_licenses.yaml"))
#print(mydata)


with open('../deploy/robokopkg/webserver/app/adocs/licenses.adoc','w') as outf:
    outf.write(header)
    for source in mydata:
        outf.write(f'|{source["url"]}[{source["name"]}] \n')
        if source['license'] is not None:
            outf.write(f'|{source["license_url"]}[{source["license"]}] \n')
        else:
            outf.write('| \n')
        if 'citation_url' in source:
            outf.write(f'|{source["citation_url"]}[Citation] \n')
        else:
            outf.write('|\n')   
        outf.write('\n')
    outf.write('|===\n')
