python buildmain.py -s omnicorp -p TAGD --start "Mitochondrial_dysfunction" --start_id "HP:0003287" 
python buildmain.py -s omnicorp -p SGPCAT --start "RILUZOLE" --start_id "CHEMBL:CHEMBL744" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCATD --start "RILUZOLE" --start_id "CHEMBL:CHEMBL744" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p PGSD --start "Parturition" --start_id "GO:0007567" 
python buildmain.py -s omnicorp -p PGD --start "Pregnancy" --start_id "GO:0007565" --end "Ehlers-Danlos Syndrome" --end_id "MONDO:0020066" 
python buildmain.py -s omnicorp -p PGD --start "Pregnancy" --start_id "GO:0007565" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "Ehlers-Danlos Syndrome" --end_id "MONDO:0020066" 
python buildmain.py -s omnicorp -p GPCATD --start "TNXB" --start_id "HGNC:11976" --end "type III Ehlers-Danlos syndrome" --end_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p GPCAT --start "GLP1" --start_id "HGNC:4191" --end "Nausea" --end_id "HP:0002018" 
python buildmain.py -s omnicorp -p DTACP --start "type 3 Ehlers-Danlos Syndrome" --start_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p DGS --start "Amyotrophic Lateral Sclerosis" --start_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p DGPCA --start "Diabetes Mellitus, Type 2" --start_id "MONDO:0005148" --end "Kidney" --end_id "UBERON:0002113" 
python buildmain.py -s omnicorp -p DGPC --start "Amyotrophic Lateral Sclerosis" --start_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCA --start "Augmentin" --start_id "MESH:D019980" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p SGPCATD --start "CEFTRIAXONE" --start_id "PUBCHEM:5361919" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "MEMANTINE" --start_id "CHEMBL:CHEMBL807" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "TALAMPANEL" --start_id "MESH:C085266" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "CELECOXIB" --start_id "CHEMBL:CHEMBL118" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "ERYTHROPOIETIN" --start_id "CHEMBL:CHEMBL1201566" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "GLATIRAMER ACETATE" --start_id "CHEMBL:CHEMBL1200430" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976"
python buildmain.py -s omnicorp -p SGPCATD --start "MINOCYCLINE" --start_id "PUBCHEM:5281021" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p DTACP --start "Ehlers-Danlos Syndrome" --start_id "MONDO:0020066" 
python buildmain.py -s omnicorp -p SGPCATD --start "PIOGLITAZONE" --start_id "CHEMBL:CHEMBL595" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "VALPROIC ACID" --start_id "CHEMBL:CHEMBL275040" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "COENZYME Q10" --start_id "CHEMBL:CHEMBL82202" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "CREATINE" --start_id "PUBCHEM:586" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "EDARAVONE" --start_id "MESH:C005435" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "DEXPRAMIPEXOLE" --start_id "MESH:C061333" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "OLESOXIME" --start_id "MESH:C522838" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "TCH346" --start_id "MESH:C111178" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "XALIPRODEN" --start_id "MESH:C462299" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "BDNF" --start_id "MESH:D019208" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "IGF-1" --start_id "CHEMBL:CHEMBL101510" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "MASITINIB" --start_id "MESH:C526575" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "LITHIUM" --start_id "CHEMBL:CHEMBL64154" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCATD --start "TIRASEMTIV" --start_id "MESH:C572767" --end "Amyotrophic Lateral Sclerosis" --end_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p SGPCAT --start "CEFTRIAXONE" --start_id "PUBCHEM:5361919" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "MEMANTINE" --start_id "CHEMBL:CHEMBL807" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "TALAMPANEL" --start_id "MESH:C085266" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "CELECOXIB" --start_id "CHEMBL:CHEMBL118" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "ERYTHROPOIETIN" --start_id "CHEMBL:CHEMBL1201566" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "GLATIRAMER ACETATE" --start_id "CHEMBL:CHEMBL1200430" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "MINOCYCLINE" --start_id "PUBCHEM:5281021" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "PIOGLITAZONE" --start_id "CHEMBL:CHEMBL595" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "VALPROIC ACID" --start_id "CHEMBL:CHEMBL275040" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "COENZYME Q10" --start_id "CHEMBL:CHEMBL82202" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "CREATINE" --start_id "PUBCHEM:586" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "EDARAVONE" --start_id "MESH:C005435" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "DEXPRAMIPEXOLE" --start_id "MESH:C061333" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "OLESOXIME" --start_id "MESH:C522838" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "TCH346" --start_id "MESH:C111178" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "XALIPRODEN" --start_id "MESH:C462299" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "BDNF" --start_id "MESH:D019208" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "IGF-1" --start_id "CHEMBL:CHEMBL101510" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "MASITINIB" --start_id "MESH:C526575" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "LITHIUM" --start_id "CHEMBL:CHEMBL64154" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCAT --start "TIRASEMTIV" --start_id "MESH:C572767" --end "Amyotrophic Lateral Sclerosis" --end_id "HP:0007354" 
python buildmain.py -s omnicorp -p SGPCATD --start "ALOGLIPTIN" --start_id "CHEMBL:CHEMBL376359" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "CANAGLIFLOZIN" --start_id "CHEMBL:CHEMBL2103841" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "DAPAGLIFLOZIN" --start_id "CHEMBL:CHEMBL429910" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "EMPAGLIFLOZIN" --start_id "CHEMBL:CHEMBL2107830" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "GLIMEPIRIDE" --start_id "CHEMBL:CHEMBL1481" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "GLIPIZIDE" --start_id "CHEMBL:CHEMBL1073" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "GLYBURIDE" --start_id "MESH:D005905" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "MIGLITOL" --start_id "CHEMBL:CHEMBL1561" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "PIOGLITAZONE" --start_id "CHEMBL:CHEMBL1715" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "TENELIGLIPTIN" --start_id "CHEMBL:CHEMBL2147777" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "TOFOGLIFLOZIN" --start_id "CHEMBL:CHEMBL2105711" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "TOLBUTAMIDE" --start_id "CHEMBL:CHEMBL782" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p SGPCATD --start "Augmentin" --start_id "MESH:D019980" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCATD --start "Amoxocillin" --start_id "CHEBI:2676" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCATD --start "Isoniazid" --start_id "MESH:D007538" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCATD --start "Nitrofurantoin" --start_id "CHEBI:71415" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCATD --start "Trimethoprim-sulfamethoxazole" --start_id "MESH:D015662" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCATD --start "Trimethoprim" --start_id "CHEBI:45924" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCATD --start "Sulfamethoxazole" --start_id "MESH:D013420" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCATD --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p SGPCATD --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p SGPCATD --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p SGPCATD --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p SGPCATD --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p SGPCATD --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p SGPCATD --start "benzophenone" --start_id "CHEBI:41308" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p SGPCATD --start "benzophenone" --start_id "CHEBI:41308" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p SGPCATD --start "benzophenone" --start_id "CHEBI:41308" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p SGPCATD --start "benzophenone" --start_id "CHEBI:41308" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p SGPCATD --start "benzophenone" --start_id "CHEBI:41308" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p SGPCATD --start "benzophenone" --start_id "CHEBI:41308" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p SGPCATD --start "PCB" --start_id "MESH:D011078" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p SGPCATD --start "PCB" --start_id "MESH:D011078" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p SGPCATD --start "PCB" --start_id "MESH:D011078" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p SGPCATD --start "PCB" --start_id "MESH:D011078" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p SGPCATD --start "PCB" --start_id "MESH:D011078" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p SGPCATD --start "PCB" --start_id "MESH:D011078" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p SGPCATD --start "DDT" --start_id "MESH:D003634" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p SGPCATD --start "DDT" --start_id "MESH:D003634" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p SGPCATD --start "DDT" --start_id "MESH:D003634" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p SGPCATD --start "DDT" --start_id "MESH:D003634" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p SGPCATD --start "DDT" --start_id "MESH:D003634" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p SGPCATD --start "DDT" --start_id "MESH:D003634" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p SGPCATD --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p SGPCATD --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p SGPCATD --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p SGPCATD --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p SGPCATD --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p SGPCATD --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p SGPCAT --start "Metformin" --start_id "CHEBI:6801" --end "Nausea" --end_id "HP:0002018" 
python buildmain.py -s omnicorp -p SGPCAT --start "Metformin" --start_id "CHEBI:6801" --end "Diarrhea" --end_id "HP:0002014" 
python buildmain.py -s omnicorp -p SGPCAT --start "Metformin" --start_id "CHEBI:6801" --end "Pancreatitis" --end_id "HP:0001733" 
python buildmain.py -s omnicorp -p SGPCA --start "Amoxocillin" --start_id "CHEBI:2676" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p SGPCA --start "Isoniazid" --start_id "MESH:D007538" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p SGPCA --start "Nitrofurantoin" --start_id "CHEBI:71415" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p SGPCA --start "Trimethoprim-sulfamethoxazole" --start_id "MESH:D015662" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p SGPCA --start "Trimethoprim" --start_id "CHEBI:45924" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p SGPCA --start "Sulfamethoxazole" --start_id "MESH:D013420" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "type 3 Ehlers-Danlos Syndrome" --end_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "Ehlers-Danlos Syndrome" --end_id "MONDO:0020066" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "type 3 Ehlers-Danlos Syndrome" --end_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p PCATD --start "Puberty" --start_id "GO:0003006" --end "Ehlers-Danlos Syndrome" --end_id "MONDO:0020066" 
python buildmain.py -s omnicorp -p PCATD --start "Puberty" --start_id "GO:0003006" --end "type 3 Ehlers-Danlos Syndrome" --end_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p PGD --start "Pregnancy" --start_id "GO:0007565" --end "type 3 Ehlers-Danlos Syndrome" --end_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p PGD --start "Embryo Development" --start_id "GO:0009795" --end "Ehlers-Danlos Syndrome" --end_id "MONDO:0020066" 
python buildmain.py -s omnicorp -p PGD --start "Embryo Development" --start_id "GO:0009795" --end "type 3 Ehlers-Danlos Syndrome" --end_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p PGD --start "Puberty" --start_id "GO:0003006" --end "Ehlers-Danlos Syndrome" --end_id "MONDO:0020066" 
python buildmain.py -s omnicorp -p PGD --start "Puberty" --start_id "GO:0003006" --end "type 3 Ehlers-Danlos Syndrome" --end_id "MONDO:0007523" 
python buildmain.py -s omnicorp -p PCATD --start "Parturition" --start_id "GO:0007567" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p PCATD --start "Parturition" --start_id "GO:0007567" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p PCATD --start "Parturition" --start_id "GO:0007567" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p PCATD --start "Parturition" --start_id "GO:0007567" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p PCATD --start "Parturition" --start_id "GO:0007567" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p PCATD --start "Parturition" --start_id "GO:0007567" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p PCATD --start "Pregnancy" --start_id "GO:0007565" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p PCATD --start "Embryo Development" --start_id "GO:0009795" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p GPCATD --start "GLP1" --start_id "HGNC:4191" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p GPCATD --start "DPP4" --start_id "HGNC:3009" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p GPCAT --start "GLP1" --start_id "HGNC:4191" --end "Diarrhea" --end_id "HP:0002014" 
python buildmain.py -s omnicorp -p GPCAT --start "GLP1" --start_id "HGNC:4191" --end "Pancreatitis" --end_id "HP:0001733" 
python buildmain.py -s omnicorp -p GPCAT --start "DPP4" --start_id "HGNC:3009" --end "Nausea" --end_id "HP:0002018" 
python buildmain.py -s omnicorp -p GPCAT --start "DPP4" --start_id "HGNC:3009" --end "Diarrhea" --end_id "HP:0002014" 
python buildmain.py -s omnicorp -p GPCAT --start "DPP4" --start_id "HGNC:3009" --end "Pancreatitis" --end_id "HP:0001733" 
python buildmain.py -s omnicorp -p PGSD --start "Pregnancy" --start_id "GO:0007565" 
python buildmain.py -s omnicorp -p PGSD --start "Embryo Development" --start_id "GO:0009795" 
python buildmain.py -s omnicorp -p PGSD --start "Parturition" --start_id "GO:0007567" 
python buildmain.py -s omnicorp -p PGSD --start "Pregnancy" --start_id "GO:0007565" 
python buildmain.py -s omnicorp -p PGSD --start "Embryo Development" --start_id "GO:0009795" 
python buildmain.py -s omnicorp -p PGD --start "Response to oxidative stress" --start_id "GO:0034599" 
python buildmain.py -s omnicorp -p PGD --start "Microtubule motor activity" --start_id "GO:0003777" 
python buildmain.py -s omnicorp -p PGD --start "neurotransmitter metabolic process" --start_id "GO:0042133" 
python buildmain.py -s omnicorp -p PGD --start "neurotransmitter uptake" --start_id "GO:0001504" 
python buildmain.py -s omnicorp -p PGD --start "neurotransmitter reuptake" --start_id "GO:0098810" 
python buildmain.py -s omnicorp -p PGD --start "neurotransmitter transport" --start_id "GO:0006836" 
python buildmain.py -s omnicorp -p PGD --start "neurotransmitter binding" --start_id "GO:0042165" 
python buildmain.py -s omnicorp -p PCATD --start "Response to oxidative stress" --start_id "GO:0034599" 
python buildmain.py -s omnicorp -p PCATD --start "Microtubule motor activity" --start_id "GO:0003777" 
python buildmain.py -s omnicorp -p PCATD --start "neurotransmitter metabolic process" --start_id "GO:0042133" 
python buildmain.py -s omnicorp -p PCATD --start "neurotransmitter uptake" --start_id "GO:0001504" 
python buildmain.py -s omnicorp -p PCATD --start "neurotransmitter reuptake" --start_id "GO:0098810" 
python buildmain.py -s omnicorp -p PCATD --start "neurotransmitter transport" --start_id "GO:0006836" 
python buildmain.py -s omnicorp -p PCATD --start "neurotransmitter binding" --start_id "GO:0042165" 
python buildmain.py -s omnicorp -p TAGD --start "Oxidative stress" --start_id "HP:0025464" 
python buildmain.py -s omnicorp -p TAGD --start "Abnormal synaptic transmission" --start_id "HP:0012535" 
python buildmain.py -s omnicorp -p SGPCA --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "Uterus" --end_id "UBERON:0000995" 
python buildmain.py -s omnicorp -p SGPCA --start "beta-hexachlorocyclohexane" --start_id "MESH:C023888" --end "Endometrium" --end_id "UBERON:00001295" 
python buildmain.py -s omnicorp -p SGPCA --start "benzophenone" --start_id "MESH:C047723" --end "Uterus" --end_id "UBERON:0000995" 
python buildmain.py -s omnicorp -p SGPCA --start "benzophenone" --start_id "MESH:C047723" --end "Endometrium" --end_id "UBERON:00001295" 
python buildmain.py -s omnicorp -p SGPCA --start "PCB" --start_id "MESH:D011078" --end "Uterus" --end_id "UBERON:0000995" 
python buildmain.py -s omnicorp -p SGPCA --start "PCB" --start_id "MESH:D011078" --end "Endometrium" --end_id "UBERON:00001295" 
python buildmain.py -s omnicorp -p SGPCA --start "DDT" --start_id "MESH:D003634" --end "Uterus" --end_id "UBERON:0000995" 
python buildmain.py -s omnicorp -p SGPCA --start "DDT" --start_id "MESH:D003634" --end "Endometrium" --end_id "UBERON:00001295" 
python buildmain.py -s omnicorp -p SGPCA --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "Uterus" --end_id "UBERON:0000995" 
python buildmain.py -s omnicorp -p SGPCA --start "Diethylstilbestrol" --start_id "MESH:D004054" --end "Endometrium" --end_id "UBERON:00001295" 
python buildmain.py -s omnicorp -p DTACP --start "pregnancy loss, recurrent, susceptibility" --start_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p DTACP --start "rare disorder related with pregnancy, childbirth and puerperium" --start_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p DTACP --start "Endometriosis" --start_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p DTACP --start "endometrial cancer" --start_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p DTACP --start "Uterine Fibroids" --start_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p DTACP --start "Uterine Disease" --start_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p DTA --start "Diabetes Mellitus, Type 2" --start_id "MONDO:0005148" --end "Kidney" --end_id "UBERON:0002113" 
python buildmain.py -s omnicorp -p SGPCATD --start "Augmentin" --start_id "MESH:D019980" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p SGPCATD --start "Amoxocillin" --start_id "CHEBI:2676" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p SGPCATD --start "Isoniazid" --start_id "MESH:D007538" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p SGPCATD --start "Nitrofurantoin" --start_id "CHEBI:71415" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p SGPCATD --start "Trimethoprim-sulfamethoxazole" --start_id "MESH:D015662" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p SGPCATD --start "Trimethoprim" --start_id "CHEBI:45924" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p SGPCATD --start "Sulfamethoxazole" --start_id "MESH:D013420" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p PGSD --start "Maternal Process involved in Parturition" --start_id "GO:0060137" 
python buildmain.py -s omnicorp -p PCATD --start "Maternal Process involved in Parturition" --start_id "GO:0060137" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p PCATD --start "Maternal Process involved in Parturition" --start_id "GO:0060137" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p PCATD --start "Maternal Process involved in Parturition" --start_id "GO:0060137" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p PCATD --start "Maternal Process involved in Parturition" --start_id "GO:0060137" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p PCATD --start "Maternal Process involved in Parturition" --start_id "GO:0060137" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p PCATD --start "Maternal Process involved in Parturition" --start_id "GO:0060137" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p PGSD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" 
python buildmain.py -s omnicorp -p PGSD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" 
python buildmain.py -s omnicorp -p PCATD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" --end "pregnancy loss, recurrent, susceptibility" --end_id "MONDO:0000144" 
python buildmain.py -s omnicorp -p PCATD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" --end "rare disorder related with pregnancy, childbirth and puerperium" --end_id "MONDO:0015582" 
python buildmain.py -s omnicorp -p PCATD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" --end "Endometriosis" --end_id "MONDO:0005133" 
python buildmain.py -s omnicorp -p PCATD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" --end "endometrial cancer" --end_id "MONDO:0002447" 
python buildmain.py -s omnicorp -p PCATD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" --end "Uterine Fibroids" --end_id "MONDO:0007886" 
python buildmain.py -s omnicorp -p PCATD --start "Fetal Process Involved in Parturition" --start_id "GO:0060138" --end "Uterine Disease" --end_id "MONDO:0002654" 
python buildmain.py -s omnicorp -p SGPCATD --start "Augmentin" --start_id "CHEMBL:CHEMBL1697738" --end "Drug Allergy" --end_id "MONDO:0000775" 
python buildmain.py -s omnicorp -p SGPCA --start "Augmentin" --start_id "CHEMBL:CHEMBL1697738" --end "Liver" --end_id "UBERON:0002107" 
python buildmain.py -s omnicorp -p SGPCATD --start "Augmentin" --start_id "CHEMBL:CHEMBL1697738" --end "Drug-induced liver injury" --end_id "MONDO:0005359" 
python buildmain.py -s omnicorp -p SGPCA --start "benzophenone" --start_id "CHEBI:41308" --end "Uterus" --end_id "UBERON:0000995" 
python buildmain.py -s omnicorp -p SGPCA --start "benzophenone" --start_id "CHEBI:41308" --end "Endometrium" --end_id "UBERON:00001295" 
python buildquicker.py -s omnicorp -p SGPCATD --start "TOLBUTAMIDE" --start_id "CHEMBL:CHEMBL782" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p DGD --start "Cystic Fibrosis" --start_id "MONDO:0009061" 
python buildmain.py -s omnicorp -p DGD --start "COPD" --start_id "MONDO:0005002" 
python buildmain.py -s omnicorp -p DGD --start "primary ciliary dyskinesia" --start_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGD --start "severe asthma" --start_id "MONDO:0004979" 
python buildmain.py -s omnicorp -p DGD --start "Cystic Fibrosis" --start_id "MONDO:0009061" --end "primary ciliary dyskinesia" --end_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGD --start "COPD" --start_id "MONDO:0005002" --end "Cystic Fibrosis" --end_id "MONDO:0009061" 
python buildmain.py -s omnicorp -p DGD --start "COPD" --start_id "MONDO:0005002" --end "primary ciliary dyskinesia" --end_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGD --start "severe asthma" --start_id "MONDO:0004979" --end "Cystic Fibrosis" --end_id "MONDO:0009061" 
python buildmain.py -s omnicorp -p DGD --start "severe asthma" --start_id "MONDO:0004979" --end "COPD" --end_id "MONDO:0005002" 
python buildmain.py -s omnicorp -p DGD --start "severe asthma" --start_id "MONDO:0004979" --end "primary ciliary dyskinesia" --end_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGD --start "Renal Cyst" --start_id "MONDO:0002473" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 
python buildmain.py -s omnicorp -p DGPGD --start "Amyotrophic Lateral Sclerosis" --start_id "MONDO:0004976" 
python buildmain.py -s omnicorp -p DGPGD --start "Cystic Fibrosis" --start_id "MONDO:0009061" 
python buildmain.py -s omnicorp -p DGPGD --start "COPD" --start_id "MONDO:0005002" 
python buildmain.py -s omnicorp -p DGPGD --start "primary ciliary dyskinesia" --start_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGPGD --start "severe asthma" --start_id "MONDO:0004979" 
python buildmain.py -s omnicorp -p DGPGD --start "Cystic Fibrosis" --start_id "MONDO:0009061" --end "primary ciliary dyskinesia" --end_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGPGD --start "COPD" --start_id "MONDO:0005002" --end "Cystic Fibrosis" --end_id "MONDO:0009061" 
python buildmain.py -s omnicorp -p DGPGD --start "COPD" --start_id "MONDO:0005002" --end "primary ciliary dyskinesia" --end_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGPGD --start "severe asthma" --start_id "MONDO:0004979" --end "Cystic Fibrosis" --end_id "MONDO:0009061" 
python buildmain.py -s omnicorp -p DGPGD --start "severe asthma" --start_id "MONDO:0004979" --end "COPD" --end_id "MONDO:0005002" 
python buildmain.py -s omnicorp -p DGPGD --start "severe asthma" --start_id "MONDO:0004979" --end "primary ciliary dyskinesia" --end_id "MONDO:0016575" 
python buildmain.py -s omnicorp -p DGPGD --start "Renal Cyst" --start_id "MONDO:0002473" --end "Diabetes Mellitus, Type 2" --end_id "MONDO:0005148" 

