DRUG='chemical_substance'
GENE='gene'
PATHWAY='pathway'
PROCESS='biological_process'
FUNCTION='molecular_function'
PROCESS_OR_FUNCTION='biological_process_or_molecular_activity'
CELL='cell'
ANATOMY='anatomical_entity'
PHENOTYPE='phenotypic_feature'
DISEASE='disease'
DISEASE_OR_PHENOTYPE='disease_or_phenotypic_feature'
GENETIC_CONDITION='genetic_condition'
DRUG_NAME = 'NAME.DRUG'
DISEASE_NAME = 'NAME.DISEASE'
PHENOTYPE_NAME = 'NAME.PHENOTYPE'
UNSPECIFIED = 'UnspecifiedType'

node_types = set([DRUG, GENE, PATHWAY, PROCESS, FUNCTION, PROCESS_OR_FUNCTION, CELL, ANATOMY, PHENOTYPE, DISEASE, DISEASE_OR_PHENOTYPE, GENETIC_CONDITION, DRUG_NAME, DISEASE_NAME, PHENOTYPE_NAME, UNSPECIFIED])

type_codes = { 'S': DRUG, 'G':GENE, 'P':PROCESS_OR_FUNCTION, 'C':CELL, 'A':ANATOMY, 'T':PHENOTYPE, 'D':DISEASE, 'X':GENETIC_CONDITION , 'W': PATHWAY, '?': UNSPECIFIED}
